/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

public enum PhoneType
{
  HOME = 0,
  WORK = 1,
  MOBILE = 2,
  OTHER = 3,
}
